# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nepalisahitya' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nepalisahitya

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'
  pod 'Firebase/Crash', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'
  pod 'Firebase/Functions', '~> 5.3.0'
  pod 'Firebase/DynamicLinks', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  # pod 'Firebase/Invites', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'Firebase/RemoteConfig', '~> 5.3.0'
  pod 'Firebase/Storage', '~> 5.3.0'
  pod 'Firebase/Performance', '~> 5.3.0'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.4'
  pod 'FBSDKLoginKit'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'GoogleSignIn'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
